import {
  Baby,
  Beer,
  Bike,
  BookOpen,
  BriefcaseBusiness,
  Bus,
  Cake,
  Car,
  Cat,
  Cigarette,
  CircleDashed,
  Coffee,
  Coins,
  Dog,
  Dumbbell,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  HandCoins,
  HeartPulse,
  House,
  Landmark,
  Laptop,
  Music,
  PartyPopper,
  PawPrint,
  Phone,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Repeat,
  RotateCcw,
  Scissors,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  Smartphone,
  Sofa,
  Sparkles,
  Ticket,
  TrainFront,
  TrendingUp,
  Tv,
  Utensils,
  Wallet,
  Wine,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react'

/**
 * Set fisso di icone per le categorie (nome lucide in kebab-case → componente).
 * Un set chiuso evita di caricare 1500 icone e funziona offline.
 */
export const ICONE_CATEGORIA: Record<string, LucideIcon> = {
  'shopping-basket': ShoppingBasket,
  'shopping-bag': ShoppingBag,
  house: House,
  bus: Bus,
  car: Car,
  fuel: Fuel,
  plane: Plane,
  'party-popper': PartyPopper,
  ticket: Ticket,
  music: Music,
  'gamepad-2': Gamepad2,
  zap: Zap,
  smartphone: Smartphone,
  laptop: Laptop,
  'heart-pulse': HeartPulse,
  dumbbell: Dumbbell,
  utensils: Utensils,
  coffee: Coffee,
  wine: Wine,
  sofa: Sofa,
  wrench: Wrench,
  shirt: Shirt,
  scissors: Scissors,
  sparkles: Sparkles,
  repeat: Repeat,
  'paw-print': PawPrint,
  baby: Baby,
  'graduation-cap': GraduationCap,
  'briefcase-business': BriefcaseBusiness,
  gift: Gift,
  'rotate-ccw': RotateCcw,
  'hand-coins': HandCoins,
  coins: Coins,
  wallet: Wallet,
  'piggy-bank': PiggyBank,
  landmark: Landmark,
  'trending-up': TrendingUp,
  cigarette: Cigarette,
  beer: Beer,
  pizza: Pizza,
  cake: Cake,
  'train-front': TrainFront,
  bike: Bike,
  'book-open': BookOpen,
  pill: Pill,
  phone: Phone,
  tv: Tv,
  cat: Cat,
  dog: Dog,
  'circle-dashed': CircleDashed,
}

export function iconaCategoria(nome: string): LucideIcon {
  return ICONE_CATEGORIA[nome] ?? CircleDashed
}
